# REPLACE VALUES BELOW WITH YOUR SPARK HOME DIRECTORY
export SPARK_HOME=/Users/sbapodara/Trainings/UCSC/Apache_Spark/ucsc-spark/spark-1.6.0-bin-hadoop2.6

# REPLACE VALUES BELOW WITH YOUR TWITTER CREDENTIALS
export CONSUMER_KEY={YOUR_CONSUMER_KEY}
export CONSUMER_SECRET={YOUR_CONSUMER_SECRET}
export ACCESS_TOKEN={YOUR_ACCESS_TOKEN}
export ACCESS_TOKEN_SECRET={YOUR_ACCESS_TOKEN_SECRET}
